namespace Sqeez.Api.Services.Interfaces
{
    /// <summary>
    /// Defines outbound application email operations.
    /// </summary>
    public interface IEmailService
    {
        /// <summary>
        /// Sends the account verification email containing the provided verification link.
        /// </summary>
        /// <param name="email">Recipient email address.</param>
        /// <param name="verificationLink">Frontend verification URL generated by the auth service.</param>
        /// <returns>A task that completes after the send operation is attempted.</returns>
        Task SendVerificationEmailAsync(string email, string verificationLink);

        /// <summary>
        /// Sends the password-reset email containing the provided reset link.
        /// </summary>
        /// <param name="email">Recipient email address.</param>
        /// <param name="resetLink">Frontend reset-password URL generated by the auth service.</param>
        /// <returns>A task that completes after the send operation is attempted.</returns>
        Task SendPasswordResetEmailAsync(string email, string resetLink);
    }
}
