/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyEmailIndexRouteImport } from './routes/verify-email/index'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy/index'
import { Route as LogoutIndexRouteImport } from './routes/logout/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as HelpIndexRouteImport } from './routes/help/index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as AppAuthenticatedRouteImport } from './routes/app/_authenticated'
import { Route as AppAuthenticatedIndexRouteImport } from './routes/app/_authenticated/index'
import { Route as AppAuthenticatedTeacherRouteImport } from './routes/app/_authenticated/teacher'
import { Route as AppAuthenticatedAdminRouteImport } from './routes/app/_authenticated/admin'
import { Route as AppAuthenticatedSubjectsIndexRouteImport } from './routes/app/_authenticated/subjects/index'
import { Route as AppAuthenticatedQuizzesIndexRouteImport } from './routes/app/_authenticated/quizzes/index'
import { Route as AppAuthenticatedProfileIndexRouteImport } from './routes/app/_authenticated/profile/index'
import { Route as AppAuthenticatedLeaderboardsIndexRouteImport } from './routes/app/_authenticated/leaderboards/index'
import { Route as AppAuthenticatedClassIndexRouteImport } from './routes/app/_authenticated/class/index'
import { Route as AppAuthenticatedProfileUserIdRouteImport } from './routes/app/_authenticated/profile/$userId'
import { Route as AppAuthenticatedClassClassIdRouteImport } from './routes/app/_authenticated/class/$classId'
import { Route as AppAuthenticatedBadgesUserIdRouteImport } from './routes/app/_authenticated/badges/$userId'
import { Route as AppAuthenticatedTeacherSubjectsIndexRouteImport } from './routes/app/_authenticated/teacher/subjects/index'
import { Route as AppAuthenticatedTeacherQuizzesIndexRouteImport } from './routes/app/_authenticated/teacher/quizzes/index'
import { Route as AppAuthenticatedSubjectsSubjectIdIndexRouteImport } from './routes/app/_authenticated/subjects/$subjectId/index'
import { Route as AppAuthenticatedQuizzesQuizIdIndexRouteImport } from './routes/app/_authenticated/quizzes/$quizId/index'
import { Route as AppAuthenticatedAdminUsersIndexRouteImport } from './routes/app/_authenticated/admin/users/index'
import { Route as AppAuthenticatedAdminSubjectsIndexRouteImport } from './routes/app/_authenticated/admin/subjects/index'
import { Route as AppAuthenticatedAdminSettingsIndexRouteImport } from './routes/app/_authenticated/admin/settings/index'
import { Route as AppAuthenticatedAdminMediaAssetsIndexRouteImport } from './routes/app/_authenticated/admin/media-assets/index'
import { Route as AppAuthenticatedAdminImportsIndexRouteImport } from './routes/app/_authenticated/admin/imports/index'
import { Route as AppAuthenticatedAdminClassesIndexRouteImport } from './routes/app/_authenticated/admin/classes/index'
import { Route as AppAuthenticatedAdminBadgesIndexRouteImport } from './routes/app/_authenticated/admin/badges/index'
import { Route as AppAuthenticatedAdminClassesClassIdRouteImport } from './routes/app/_authenticated/admin/classes/$classId'
import { Route as AppAuthenticatedTeacherSubjectsSubjectIdIndexRouteImport } from './routes/app/_authenticated/teacher/subjects/$subjectId/index'
import { Route as AppAuthenticatedSubjectsSubjectIdStudentsIndexRouteImport } from './routes/app/_authenticated/subjects/$subjectId/students/index'
import { Route as AppAuthenticatedSubjectsSubjectIdQuizzesIndexRouteImport } from './routes/app/_authenticated/subjects/$subjectId/quizzes/index'
import { Route as AppAuthenticatedQuizzesQuizIdResultsIndexRouteImport } from './routes/app/_authenticated/quizzes/$quizId/results/index'
import { Route as AppAuthenticatedQuizzesQuizIdPlayIndexRouteImport } from './routes/app/_authenticated/quizzes/$quizId/play/index'
import { Route as AppAuthenticatedQuizzesQuizIdBuilderIndexRouteImport } from './routes/app/_authenticated/quizzes/$quizId/builder/index'
import { Route as AppAuthenticatedQuizzesQuizIdAttemptsIndexRouteImport } from './routes/app/_authenticated/quizzes/$quizId/attempts/index'
import { Route as AppAuthenticatedQuizzesQuizIdAttemptsAttemptIdRouteImport } from './routes/app/_authenticated/quizzes/$quizId/attempts/$attemptId'
import { Route as AppAuthenticatedTeacherSubjectsSubjectIdStudentsIndexRouteImport } from './routes/app/_authenticated/teacher/subjects/$subjectId/students/index'
import { Route as AppAuthenticatedTeacherSubjectsSubjectIdQuizIdIndexRouteImport } from './routes/app/_authenticated/teacher/subjects/$subjectId/$quizId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailIndexRoute = VerifyEmailIndexRouteImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutIndexRoute = LogoutIndexRouteImport.update({
  id: '/logout/',
  path: '/logout/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedRoute = AppAuthenticatedRouteImport.update({
  id: '/app/_authenticated',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthenticatedIndexRoute = AppAuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthenticatedRoute,
} as any)
const AppAuthenticatedTeacherRoute = AppAuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AppAuthenticatedRoute,
} as any)
const AppAuthenticatedAdminRoute = AppAuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppAuthenticatedRoute,
} as any)
const AppAuthenticatedSubjectsIndexRoute =
  AppAuthenticatedSubjectsIndexRouteImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedQuizzesIndexRoute =
  AppAuthenticatedQuizzesIndexRouteImport.update({
    id: '/quizzes/',
    path: '/quizzes/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedProfileIndexRoute =
  AppAuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedLeaderboardsIndexRoute =
  AppAuthenticatedLeaderboardsIndexRouteImport.update({
    id: '/leaderboards/',
    path: '/leaderboards/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedClassIndexRoute =
  AppAuthenticatedClassIndexRouteImport.update({
    id: '/class/',
    path: '/class/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedProfileUserIdRoute =
  AppAuthenticatedProfileUserIdRouteImport.update({
    id: '/profile/$userId',
    path: '/profile/$userId',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedClassClassIdRoute =
  AppAuthenticatedClassClassIdRouteImport.update({
    id: '/class/$classId',
    path: '/class/$classId',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedBadgesUserIdRoute =
  AppAuthenticatedBadgesUserIdRouteImport.update({
    id: '/badges/$userId',
    path: '/badges/$userId',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedTeacherSubjectsIndexRoute =
  AppAuthenticatedTeacherSubjectsIndexRouteImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => AppAuthenticatedTeacherRoute,
  } as any)
const AppAuthenticatedTeacherQuizzesIndexRoute =
  AppAuthenticatedTeacherQuizzesIndexRouteImport.update({
    id: '/quizzes/',
    path: '/quizzes/',
    getParentRoute: () => AppAuthenticatedTeacherRoute,
  } as any)
const AppAuthenticatedSubjectsSubjectIdIndexRoute =
  AppAuthenticatedSubjectsSubjectIdIndexRouteImport.update({
    id: '/subjects/$subjectId/',
    path: '/subjects/$subjectId/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedQuizzesQuizIdIndexRoute =
  AppAuthenticatedQuizzesQuizIdIndexRouteImport.update({
    id: '/quizzes/$quizId/',
    path: '/quizzes/$quizId/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedAdminUsersIndexRoute =
  AppAuthenticatedAdminUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AppAuthenticatedAdminRoute,
  } as any)
const AppAuthenticatedAdminSubjectsIndexRoute =
  AppAuthenticatedAdminSubjectsIndexRouteImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => AppAuthenticatedAdminRoute,
  } as any)
const AppAuthenticatedAdminSettingsIndexRoute =
  AppAuthenticatedAdminSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AppAuthenticatedAdminRoute,
  } as any)
const AppAuthenticatedAdminMediaAssetsIndexRoute =
  AppAuthenticatedAdminMediaAssetsIndexRouteImport.update({
    id: '/media-assets/',
    path: '/media-assets/',
    getParentRoute: () => AppAuthenticatedAdminRoute,
  } as any)
const AppAuthenticatedAdminImportsIndexRoute =
  AppAuthenticatedAdminImportsIndexRouteImport.update({
    id: '/imports/',
    path: '/imports/',
    getParentRoute: () => AppAuthenticatedAdminRoute,
  } as any)
const AppAuthenticatedAdminClassesIndexRoute =
  AppAuthenticatedAdminClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AppAuthenticatedAdminRoute,
  } as any)
const AppAuthenticatedAdminBadgesIndexRoute =
  AppAuthenticatedAdminBadgesIndexRouteImport.update({
    id: '/badges/',
    path: '/badges/',
    getParentRoute: () => AppAuthenticatedAdminRoute,
  } as any)
const AppAuthenticatedAdminClassesClassIdRoute =
  AppAuthenticatedAdminClassesClassIdRouteImport.update({
    id: '/classes/$classId',
    path: '/classes/$classId',
    getParentRoute: () => AppAuthenticatedAdminRoute,
  } as any)
const AppAuthenticatedTeacherSubjectsSubjectIdIndexRoute =
  AppAuthenticatedTeacherSubjectsSubjectIdIndexRouteImport.update({
    id: '/subjects/$subjectId/',
    path: '/subjects/$subjectId/',
    getParentRoute: () => AppAuthenticatedTeacherRoute,
  } as any)
const AppAuthenticatedSubjectsSubjectIdStudentsIndexRoute =
  AppAuthenticatedSubjectsSubjectIdStudentsIndexRouteImport.update({
    id: '/subjects/$subjectId/students/',
    path: '/subjects/$subjectId/students/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedSubjectsSubjectIdQuizzesIndexRoute =
  AppAuthenticatedSubjectsSubjectIdQuizzesIndexRouteImport.update({
    id: '/subjects/$subjectId/quizzes/',
    path: '/subjects/$subjectId/quizzes/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedQuizzesQuizIdResultsIndexRoute =
  AppAuthenticatedQuizzesQuizIdResultsIndexRouteImport.update({
    id: '/quizzes/$quizId/results/',
    path: '/quizzes/$quizId/results/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedQuizzesQuizIdPlayIndexRoute =
  AppAuthenticatedQuizzesQuizIdPlayIndexRouteImport.update({
    id: '/quizzes/$quizId/play/',
    path: '/quizzes/$quizId/play/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedQuizzesQuizIdBuilderIndexRoute =
  AppAuthenticatedQuizzesQuizIdBuilderIndexRouteImport.update({
    id: '/quizzes/$quizId/builder/',
    path: '/quizzes/$quizId/builder/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedQuizzesQuizIdAttemptsIndexRoute =
  AppAuthenticatedQuizzesQuizIdAttemptsIndexRouteImport.update({
    id: '/quizzes/$quizId/attempts/',
    path: '/quizzes/$quizId/attempts/',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedQuizzesQuizIdAttemptsAttemptIdRoute =
  AppAuthenticatedQuizzesQuizIdAttemptsAttemptIdRouteImport.update({
    id: '/quizzes/$quizId/attempts/$attemptId',
    path: '/quizzes/$quizId/attempts/$attemptId',
    getParentRoute: () => AppAuthenticatedRoute,
  } as any)
const AppAuthenticatedTeacherSubjectsSubjectIdStudentsIndexRoute =
  AppAuthenticatedTeacherSubjectsSubjectIdStudentsIndexRouteImport.update({
    id: '/subjects/$subjectId/students/',
    path: '/subjects/$subjectId/students/',
    getParentRoute: () => AppAuthenticatedTeacherRoute,
  } as any)
const AppAuthenticatedTeacherSubjectsSubjectIdQuizIdIndexRoute =
  AppAuthenticatedTeacherSubjectsSubjectIdQuizIdIndexRouteImport.update({
    id: '/subjects/$subjectId/$quizId/',
    path: '/subjects/$subjectId/$quizId/',
    getParentRoute: () => AppAuthenticatedTeacherRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAuthenticatedRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/help/': typeof HelpIndexRoute
  '/login/': typeof LoginIndexRoute
  '/logout/': typeof LogoutIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
  '/app/admin': typeof AppAuthenticatedAdminRouteWithChildren
  '/app/teacher': typeof AppAuthenticatedTeacherRouteWithChildren
  '/app/': typeof AppAuthenticatedIndexRoute
  '/app/badges/$userId': typeof AppAuthenticatedBadgesUserIdRoute
  '/app/class/$classId': typeof AppAuthenticatedClassClassIdRoute
  '/app/profile/$userId': typeof AppAuthenticatedProfileUserIdRoute
  '/app/class/': typeof AppAuthenticatedClassIndexRoute
  '/app/leaderboards/': typeof AppAuthenticatedLeaderboardsIndexRoute
  '/app/profile/': typeof AppAuthenticatedProfileIndexRoute
  '/app/quizzes/': typeof AppAuthenticatedQuizzesIndexRoute
  '/app/subjects/': typeof AppAuthenticatedSubjectsIndexRoute
  '/app/admin/classes/$classId': typeof AppAuthenticatedAdminClassesClassIdRoute
  '/app/admin/badges/': typeof AppAuthenticatedAdminBadgesIndexRoute
  '/app/admin/classes/': typeof AppAuthenticatedAdminClassesIndexRoute
  '/app/admin/imports/': typeof AppAuthenticatedAdminImportsIndexRoute
  '/app/admin/media-assets/': typeof AppAuthenticatedAdminMediaAssetsIndexRoute
  '/app/admin/settings/': typeof AppAuthenticatedAdminSettingsIndexRoute
  '/app/admin/subjects/': typeof AppAuthenticatedAdminSubjectsIndexRoute
  '/app/admin/users/': typeof AppAuthenticatedAdminUsersIndexRoute
  '/app/quizzes/$quizId/': typeof AppAuthenticatedQuizzesQuizIdIndexRoute
  '/app/subjects/$subjectId/': typeof AppAuthenticatedSubjectsSubjectIdIndexRoute
  '/app/teacher/quizzes/': typeof AppAuthenticatedTeacherQuizzesIndexRoute
  '/app/teacher/subjects/': typeof AppAuthenticatedTeacherSubjectsIndexRoute
  '/app/quizzes/$quizId/attempts/$attemptId': typeof AppAuthenticatedQuizzesQuizIdAttemptsAttemptIdRoute
  '/app/quizzes/$quizId/attempts/': typeof AppAuthenticatedQuizzesQuizIdAttemptsIndexRoute
  '/app/quizzes/$quizId/builder/': typeof AppAuthenticatedQuizzesQuizIdBuilderIndexRoute
  '/app/quizzes/$quizId/play/': typeof AppAuthenticatedQuizzesQuizIdPlayIndexRoute
  '/app/quizzes/$quizId/results/': typeof AppAuthenticatedQuizzesQuizIdResultsIndexRoute
  '/app/subjects/$subjectId/quizzes/': typeof AppAuthenticatedSubjectsSubjectIdQuizzesIndexRoute
  '/app/subjects/$subjectId/students/': typeof AppAuthenticatedSubjectsSubjectIdStudentsIndexRoute
  '/app/teacher/subjects/$subjectId/': typeof AppAuthenticatedTeacherSubjectsSubjectIdIndexRoute
  '/app/teacher/subjects/$subjectId/$quizId/': typeof AppAuthenticatedTeacherSubjectsSubjectIdQuizIdIndexRoute
  '/app/teacher/subjects/$subjectId/students/': typeof AppAuthenticatedTeacherSubjectsSubjectIdStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/help': typeof HelpIndexRoute
  '/login': typeof LoginIndexRoute
  '/logout': typeof LogoutIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/register': typeof RegisterIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/terms': typeof TermsIndexRoute
  '/verify-email': typeof VerifyEmailIndexRoute
  '/app/admin': typeof AppAuthenticatedAdminRouteWithChildren
  '/app/teacher': typeof AppAuthenticatedTeacherRouteWithChildren
  '/app': typeof AppAuthenticatedIndexRoute
  '/app/badges/$userId': typeof AppAuthenticatedBadgesUserIdRoute
  '/app/class/$classId': typeof AppAuthenticatedClassClassIdRoute
  '/app/profile/$userId': typeof AppAuthenticatedProfileUserIdRoute
  '/app/class': typeof AppAuthenticatedClassIndexRoute
  '/app/leaderboards': typeof AppAuthenticatedLeaderboardsIndexRoute
  '/app/profile': typeof AppAuthenticatedProfileIndexRoute
  '/app/quizzes': typeof AppAuthenticatedQuizzesIndexRoute
  '/app/subjects': typeof AppAuthenticatedSubjectsIndexRoute
  '/app/admin/classes/$classId': typeof AppAuthenticatedAdminClassesClassIdRoute
  '/app/admin/badges': typeof AppAuthenticatedAdminBadgesIndexRoute
  '/app/admin/classes': typeof AppAuthenticatedAdminClassesIndexRoute
  '/app/admin/imports': typeof AppAuthenticatedAdminImportsIndexRoute
  '/app/admin/media-assets': typeof AppAuthenticatedAdminMediaAssetsIndexRoute
  '/app/admin/settings': typeof AppAuthenticatedAdminSettingsIndexRoute
  '/app/admin/subjects': typeof AppAuthenticatedAdminSubjectsIndexRoute
  '/app/admin/users': typeof AppAuthenticatedAdminUsersIndexRoute
  '/app/quizzes/$quizId': typeof AppAuthenticatedQuizzesQuizIdIndexRoute
  '/app/subjects/$subjectId': typeof AppAuthenticatedSubjectsSubjectIdIndexRoute
  '/app/teacher/quizzes': typeof AppAuthenticatedTeacherQuizzesIndexRoute
  '/app/teacher/subjects': typeof AppAuthenticatedTeacherSubjectsIndexRoute
  '/app/quizzes/$quizId/attempts/$attemptId': typeof AppAuthenticatedQuizzesQuizIdAttemptsAttemptIdRoute
  '/app/quizzes/$quizId/attempts': typeof AppAuthenticatedQuizzesQuizIdAttemptsIndexRoute
  '/app/quizzes/$quizId/builder': typeof AppAuthenticatedQuizzesQuizIdBuilderIndexRoute
  '/app/quizzes/$quizId/play': typeof AppAuthenticatedQuizzesQuizIdPlayIndexRoute
  '/app/quizzes/$quizId/results': typeof AppAuthenticatedQuizzesQuizIdResultsIndexRoute
  '/app/subjects/$subjectId/quizzes': typeof AppAuthenticatedSubjectsSubjectIdQuizzesIndexRoute
  '/app/subjects/$subjectId/students': typeof AppAuthenticatedSubjectsSubjectIdStudentsIndexRoute
  '/app/teacher/subjects/$subjectId': typeof AppAuthenticatedTeacherSubjectsSubjectIdIndexRoute
  '/app/teacher/subjects/$subjectId/$quizId': typeof AppAuthenticatedTeacherSubjectsSubjectIdQuizIdIndexRoute
  '/app/teacher/subjects/$subjectId/students': typeof AppAuthenticatedTeacherSubjectsSubjectIdStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/_authenticated': typeof AppAuthenticatedRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/help/': typeof HelpIndexRoute
  '/login/': typeof LoginIndexRoute
  '/logout/': typeof LogoutIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
  '/app/_authenticated/admin': typeof AppAuthenticatedAdminRouteWithChildren
  '/app/_authenticated/teacher': typeof AppAuthenticatedTeacherRouteWithChildren
  '/app/_authenticated/': typeof AppAuthenticatedIndexRoute
  '/app/_authenticated/badges/$userId': typeof AppAuthenticatedBadgesUserIdRoute
  '/app/_authenticated/class/$classId': typeof AppAuthenticatedClassClassIdRoute
  '/app/_authenticated/profile/$userId': typeof AppAuthenticatedProfileUserIdRoute
  '/app/_authenticated/class/': typeof AppAuthenticatedClassIndexRoute
  '/app/_authenticated/leaderboards/': typeof AppAuthenticatedLeaderboardsIndexRoute
  '/app/_authenticated/profile/': typeof AppAuthenticatedProfileIndexRoute
  '/app/_authenticated/quizzes/': typeof AppAuthenticatedQuizzesIndexRoute
  '/app/_authenticated/subjects/': typeof AppAuthenticatedSubjectsIndexRoute
  '/app/_authenticated/admin/classes/$classId': typeof AppAuthenticatedAdminClassesClassIdRoute
  '/app/_authenticated/admin/badges/': typeof AppAuthenticatedAdminBadgesIndexRoute
  '/app/_authenticated/admin/classes/': typeof AppAuthenticatedAdminClassesIndexRoute
  '/app/_authenticated/admin/imports/': typeof AppAuthenticatedAdminImportsIndexRoute
  '/app/_authenticated/admin/media-assets/': typeof AppAuthenticatedAdminMediaAssetsIndexRoute
  '/app/_authenticated/admin/settings/': typeof AppAuthenticatedAdminSettingsIndexRoute
  '/app/_authenticated/admin/subjects/': typeof AppAuthenticatedAdminSubjectsIndexRoute
  '/app/_authenticated/admin/users/': typeof AppAuthenticatedAdminUsersIndexRoute
  '/app/_authenticated/quizzes/$quizId/': typeof AppAuthenticatedQuizzesQuizIdIndexRoute
  '/app/_authenticated/subjects/$subjectId/': typeof AppAuthenticatedSubjectsSubjectIdIndexRoute
  '/app/_authenticated/teacher/quizzes/': typeof AppAuthenticatedTeacherQuizzesIndexRoute
  '/app/_authenticated/teacher/subjects/': typeof AppAuthenticatedTeacherSubjectsIndexRoute
  '/app/_authenticated/quizzes/$quizId/attempts/$attemptId': typeof AppAuthenticatedQuizzesQuizIdAttemptsAttemptIdRoute
  '/app/_authenticated/quizzes/$quizId/attempts/': typeof AppAuthenticatedQuizzesQuizIdAttemptsIndexRoute
  '/app/_authenticated/quizzes/$quizId/builder/': typeof AppAuthenticatedQuizzesQuizIdBuilderIndexRoute
  '/app/_authenticated/quizzes/$quizId/play/': typeof AppAuthenticatedQuizzesQuizIdPlayIndexRoute
  '/app/_authenticated/quizzes/$quizId/results/': typeof AppAuthenticatedQuizzesQuizIdResultsIndexRoute
  '/app/_authenticated/subjects/$subjectId/quizzes/': typeof AppAuthenticatedSubjectsSubjectIdQuizzesIndexRoute
  '/app/_authenticated/subjects/$subjectId/students/': typeof AppAuthenticatedSubjectsSubjectIdStudentsIndexRoute
  '/app/_authenticated/teacher/subjects/$subjectId/': typeof AppAuthenticatedTeacherSubjectsSubjectIdIndexRoute
  '/app/_authenticated/teacher/subjects/$subjectId/$quizId/': typeof AppAuthenticatedTeacherSubjectsSubjectIdQuizIdIndexRoute
  '/app/_authenticated/teacher/subjects/$subjectId/students/': typeof AppAuthenticatedTeacherSubjectsSubjectIdStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/about/'
    | '/forgot-password/'
    | '/help/'
    | '/login/'
    | '/logout/'
    | '/privacy/'
    | '/register/'
    | '/reset-password/'
    | '/terms/'
    | '/verify-email/'
    | '/app/admin'
    | '/app/teacher'
    | '/app/'
    | '/app/badges/$userId'
    | '/app/class/$classId'
    | '/app/profile/$userId'
    | '/app/class/'
    | '/app/leaderboards/'
    | '/app/profile/'
    | '/app/quizzes/'
    | '/app/subjects/'
    | '/app/admin/classes/$classId'
    | '/app/admin/badges/'
    | '/app/admin/classes/'
    | '/app/admin/imports/'
    | '/app/admin/media-assets/'
    | '/app/admin/settings/'
    | '/app/admin/subjects/'
    | '/app/admin/users/'
    | '/app/quizzes/$quizId/'
    | '/app/subjects/$subjectId/'
    | '/app/teacher/quizzes/'
    | '/app/teacher/subjects/'
    | '/app/quizzes/$quizId/attempts/$attemptId'
    | '/app/quizzes/$quizId/attempts/'
    | '/app/quizzes/$quizId/builder/'
    | '/app/quizzes/$quizId/play/'
    | '/app/quizzes/$quizId/results/'
    | '/app/subjects/$subjectId/quizzes/'
    | '/app/subjects/$subjectId/students/'
    | '/app/teacher/subjects/$subjectId/'
    | '/app/teacher/subjects/$subjectId/$quizId/'
    | '/app/teacher/subjects/$subjectId/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/logout'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/app/admin'
    | '/app/teacher'
    | '/app'
    | '/app/badges/$userId'
    | '/app/class/$classId'
    | '/app/profile/$userId'
    | '/app/class'
    | '/app/leaderboards'
    | '/app/profile'
    | '/app/quizzes'
    | '/app/subjects'
    | '/app/admin/classes/$classId'
    | '/app/admin/badges'
    | '/app/admin/classes'
    | '/app/admin/imports'
    | '/app/admin/media-assets'
    | '/app/admin/settings'
    | '/app/admin/subjects'
    | '/app/admin/users'
    | '/app/quizzes/$quizId'
    | '/app/subjects/$subjectId'
    | '/app/teacher/quizzes'
    | '/app/teacher/subjects'
    | '/app/quizzes/$quizId/attempts/$attemptId'
    | '/app/quizzes/$quizId/attempts'
    | '/app/quizzes/$quizId/builder'
    | '/app/quizzes/$quizId/play'
    | '/app/quizzes/$quizId/results'
    | '/app/subjects/$subjectId/quizzes'
    | '/app/subjects/$subjectId/students'
    | '/app/teacher/subjects/$subjectId'
    | '/app/teacher/subjects/$subjectId/$quizId'
    | '/app/teacher/subjects/$subjectId/students'
  id:
    | '__root__'
    | '/'
    | '/app/_authenticated'
    | '/about/'
    | '/forgot-password/'
    | '/help/'
    | '/login/'
    | '/logout/'
    | '/privacy/'
    | '/register/'
    | '/reset-password/'
    | '/terms/'
    | '/verify-email/'
    | '/app/_authenticated/admin'
    | '/app/_authenticated/teacher'
    | '/app/_authenticated/'
    | '/app/_authenticated/badges/$userId'
    | '/app/_authenticated/class/$classId'
    | '/app/_authenticated/profile/$userId'
    | '/app/_authenticated/class/'
    | '/app/_authenticated/leaderboards/'
    | '/app/_authenticated/profile/'
    | '/app/_authenticated/quizzes/'
    | '/app/_authenticated/subjects/'
    | '/app/_authenticated/admin/classes/$classId'
    | '/app/_authenticated/admin/badges/'
    | '/app/_authenticated/admin/classes/'
    | '/app/_authenticated/admin/imports/'
    | '/app/_authenticated/admin/media-assets/'
    | '/app/_authenticated/admin/settings/'
    | '/app/_authenticated/admin/subjects/'
    | '/app/_authenticated/admin/users/'
    | '/app/_authenticated/quizzes/$quizId/'
    | '/app/_authenticated/subjects/$subjectId/'
    | '/app/_authenticated/teacher/quizzes/'
    | '/app/_authenticated/teacher/subjects/'
    | '/app/_authenticated/quizzes/$quizId/attempts/$attemptId'
    | '/app/_authenticated/quizzes/$quizId/attempts/'
    | '/app/_authenticated/quizzes/$quizId/builder/'
    | '/app/_authenticated/quizzes/$quizId/play/'
    | '/app/_authenticated/quizzes/$quizId/results/'
    | '/app/_authenticated/subjects/$subjectId/quizzes/'
    | '/app/_authenticated/subjects/$subjectId/students/'
    | '/app/_authenticated/teacher/subjects/$subjectId/'
    | '/app/_authenticated/teacher/subjects/$subjectId/$quizId/'
    | '/app/_authenticated/teacher/subjects/$subjectId/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppAuthenticatedRoute: typeof AppAuthenticatedRouteWithChildren
  AboutIndexRoute: typeof AboutIndexRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  HelpIndexRoute: typeof HelpIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  LogoutIndexRoute: typeof LogoutIndexRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
  VerifyEmailIndexRoute: typeof VerifyEmailIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/': {
      id: '/verify-email/'
      path: '/verify-email'
      fullPath: '/verify-email/'
      preLoaderRoute: typeof VerifyEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout/': {
      id: '/logout/'
      path: '/logout'
      fullPath: '/logout/'
      preLoaderRoute: typeof LogoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated': {
      id: '/app/_authenticated'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authenticated/': {
      id: '/app/_authenticated/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthenticatedIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/teacher': {
      id: '/app/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/app/teacher'
      preLoaderRoute: typeof AppAuthenticatedTeacherRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/admin': {
      id: '/app/_authenticated/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAuthenticatedAdminRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/subjects/': {
      id: '/app/_authenticated/subjects/'
      path: '/subjects'
      fullPath: '/app/subjects/'
      preLoaderRoute: typeof AppAuthenticatedSubjectsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/quizzes/': {
      id: '/app/_authenticated/quizzes/'
      path: '/quizzes'
      fullPath: '/app/quizzes/'
      preLoaderRoute: typeof AppAuthenticatedQuizzesIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/profile/': {
      id: '/app/_authenticated/profile/'
      path: '/profile'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AppAuthenticatedProfileIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/leaderboards/': {
      id: '/app/_authenticated/leaderboards/'
      path: '/leaderboards'
      fullPath: '/app/leaderboards/'
      preLoaderRoute: typeof AppAuthenticatedLeaderboardsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/class/': {
      id: '/app/_authenticated/class/'
      path: '/class'
      fullPath: '/app/class/'
      preLoaderRoute: typeof AppAuthenticatedClassIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/profile/$userId': {
      id: '/app/_authenticated/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/app/profile/$userId'
      preLoaderRoute: typeof AppAuthenticatedProfileUserIdRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/class/$classId': {
      id: '/app/_authenticated/class/$classId'
      path: '/class/$classId'
      fullPath: '/app/class/$classId'
      preLoaderRoute: typeof AppAuthenticatedClassClassIdRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/badges/$userId': {
      id: '/app/_authenticated/badges/$userId'
      path: '/badges/$userId'
      fullPath: '/app/badges/$userId'
      preLoaderRoute: typeof AppAuthenticatedBadgesUserIdRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/teacher/subjects/': {
      id: '/app/_authenticated/teacher/subjects/'
      path: '/subjects'
      fullPath: '/app/teacher/subjects/'
      preLoaderRoute: typeof AppAuthenticatedTeacherSubjectsIndexRouteImport
      parentRoute: typeof AppAuthenticatedTeacherRoute
    }
    '/app/_authenticated/teacher/quizzes/': {
      id: '/app/_authenticated/teacher/quizzes/'
      path: '/quizzes'
      fullPath: '/app/teacher/quizzes/'
      preLoaderRoute: typeof AppAuthenticatedTeacherQuizzesIndexRouteImport
      parentRoute: typeof AppAuthenticatedTeacherRoute
    }
    '/app/_authenticated/subjects/$subjectId/': {
      id: '/app/_authenticated/subjects/$subjectId/'
      path: '/subjects/$subjectId'
      fullPath: '/app/subjects/$subjectId/'
      preLoaderRoute: typeof AppAuthenticatedSubjectsSubjectIdIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/quizzes/$quizId/': {
      id: '/app/_authenticated/quizzes/$quizId/'
      path: '/quizzes/$quizId'
      fullPath: '/app/quizzes/$quizId/'
      preLoaderRoute: typeof AppAuthenticatedQuizzesQuizIdIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/admin/users/': {
      id: '/app/_authenticated/admin/users/'
      path: '/users'
      fullPath: '/app/admin/users/'
      preLoaderRoute: typeof AppAuthenticatedAdminUsersIndexRouteImport
      parentRoute: typeof AppAuthenticatedAdminRoute
    }
    '/app/_authenticated/admin/subjects/': {
      id: '/app/_authenticated/admin/subjects/'
      path: '/subjects'
      fullPath: '/app/admin/subjects/'
      preLoaderRoute: typeof AppAuthenticatedAdminSubjectsIndexRouteImport
      parentRoute: typeof AppAuthenticatedAdminRoute
    }
    '/app/_authenticated/admin/settings/': {
      id: '/app/_authenticated/admin/settings/'
      path: '/settings'
      fullPath: '/app/admin/settings/'
      preLoaderRoute: typeof AppAuthenticatedAdminSettingsIndexRouteImport
      parentRoute: typeof AppAuthenticatedAdminRoute
    }
    '/app/_authenticated/admin/media-assets/': {
      id: '/app/_authenticated/admin/media-assets/'
      path: '/media-assets'
      fullPath: '/app/admin/media-assets/'
      preLoaderRoute: typeof AppAuthenticatedAdminMediaAssetsIndexRouteImport
      parentRoute: typeof AppAuthenticatedAdminRoute
    }
    '/app/_authenticated/admin/imports/': {
      id: '/app/_authenticated/admin/imports/'
      path: '/imports'
      fullPath: '/app/admin/imports/'
      preLoaderRoute: typeof AppAuthenticatedAdminImportsIndexRouteImport
      parentRoute: typeof AppAuthenticatedAdminRoute
    }
    '/app/_authenticated/admin/classes/': {
      id: '/app/_authenticated/admin/classes/'
      path: '/classes'
      fullPath: '/app/admin/classes/'
      preLoaderRoute: typeof AppAuthenticatedAdminClassesIndexRouteImport
      parentRoute: typeof AppAuthenticatedAdminRoute
    }
    '/app/_authenticated/admin/badges/': {
      id: '/app/_authenticated/admin/badges/'
      path: '/badges'
      fullPath: '/app/admin/badges/'
      preLoaderRoute: typeof AppAuthenticatedAdminBadgesIndexRouteImport
      parentRoute: typeof AppAuthenticatedAdminRoute
    }
    '/app/_authenticated/admin/classes/$classId': {
      id: '/app/_authenticated/admin/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/app/admin/classes/$classId'
      preLoaderRoute: typeof AppAuthenticatedAdminClassesClassIdRouteImport
      parentRoute: typeof AppAuthenticatedAdminRoute
    }
    '/app/_authenticated/teacher/subjects/$subjectId/': {
      id: '/app/_authenticated/teacher/subjects/$subjectId/'
      path: '/subjects/$subjectId'
      fullPath: '/app/teacher/subjects/$subjectId/'
      preLoaderRoute: typeof AppAuthenticatedTeacherSubjectsSubjectIdIndexRouteImport
      parentRoute: typeof AppAuthenticatedTeacherRoute
    }
    '/app/_authenticated/subjects/$subjectId/students/': {
      id: '/app/_authenticated/subjects/$subjectId/students/'
      path: '/subjects/$subjectId/students'
      fullPath: '/app/subjects/$subjectId/students/'
      preLoaderRoute: typeof AppAuthenticatedSubjectsSubjectIdStudentsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/subjects/$subjectId/quizzes/': {
      id: '/app/_authenticated/subjects/$subjectId/quizzes/'
      path: '/subjects/$subjectId/quizzes'
      fullPath: '/app/subjects/$subjectId/quizzes/'
      preLoaderRoute: typeof AppAuthenticatedSubjectsSubjectIdQuizzesIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/quizzes/$quizId/results/': {
      id: '/app/_authenticated/quizzes/$quizId/results/'
      path: '/quizzes/$quizId/results'
      fullPath: '/app/quizzes/$quizId/results/'
      preLoaderRoute: typeof AppAuthenticatedQuizzesQuizIdResultsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/quizzes/$quizId/play/': {
      id: '/app/_authenticated/quizzes/$quizId/play/'
      path: '/quizzes/$quizId/play'
      fullPath: '/app/quizzes/$quizId/play/'
      preLoaderRoute: typeof AppAuthenticatedQuizzesQuizIdPlayIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/quizzes/$quizId/builder/': {
      id: '/app/_authenticated/quizzes/$quizId/builder/'
      path: '/quizzes/$quizId/builder'
      fullPath: '/app/quizzes/$quizId/builder/'
      preLoaderRoute: typeof AppAuthenticatedQuizzesQuizIdBuilderIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/quizzes/$quizId/attempts/': {
      id: '/app/_authenticated/quizzes/$quizId/attempts/'
      path: '/quizzes/$quizId/attempts'
      fullPath: '/app/quizzes/$quizId/attempts/'
      preLoaderRoute: typeof AppAuthenticatedQuizzesQuizIdAttemptsIndexRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/quizzes/$quizId/attempts/$attemptId': {
      id: '/app/_authenticated/quizzes/$quizId/attempts/$attemptId'
      path: '/quizzes/$quizId/attempts/$attemptId'
      fullPath: '/app/quizzes/$quizId/attempts/$attemptId'
      preLoaderRoute: typeof AppAuthenticatedQuizzesQuizIdAttemptsAttemptIdRouteImport
      parentRoute: typeof AppAuthenticatedRoute
    }
    '/app/_authenticated/teacher/subjects/$subjectId/students/': {
      id: '/app/_authenticated/teacher/subjects/$subjectId/students/'
      path: '/subjects/$subjectId/students'
      fullPath: '/app/teacher/subjects/$subjectId/students/'
      preLoaderRoute: typeof AppAuthenticatedTeacherSubjectsSubjectIdStudentsIndexRouteImport
      parentRoute: typeof AppAuthenticatedTeacherRoute
    }
    '/app/_authenticated/teacher/subjects/$subjectId/$quizId/': {
      id: '/app/_authenticated/teacher/subjects/$subjectId/$quizId/'
      path: '/subjects/$subjectId/$quizId'
      fullPath: '/app/teacher/subjects/$subjectId/$quizId/'
      preLoaderRoute: typeof AppAuthenticatedTeacherSubjectsSubjectIdQuizIdIndexRouteImport
      parentRoute: typeof AppAuthenticatedTeacherRoute
    }
  }
}

interface AppAuthenticatedAdminRouteChildren {
  AppAuthenticatedAdminClassesClassIdRoute: typeof AppAuthenticatedAdminClassesClassIdRoute
  AppAuthenticatedAdminBadgesIndexRoute: typeof AppAuthenticatedAdminBadgesIndexRoute
  AppAuthenticatedAdminClassesIndexRoute: typeof AppAuthenticatedAdminClassesIndexRoute
  AppAuthenticatedAdminImportsIndexRoute: typeof AppAuthenticatedAdminImportsIndexRoute
  AppAuthenticatedAdminMediaAssetsIndexRoute: typeof AppAuthenticatedAdminMediaAssetsIndexRoute
  AppAuthenticatedAdminSettingsIndexRoute: typeof AppAuthenticatedAdminSettingsIndexRoute
  AppAuthenticatedAdminSubjectsIndexRoute: typeof AppAuthenticatedAdminSubjectsIndexRoute
  AppAuthenticatedAdminUsersIndexRoute: typeof AppAuthenticatedAdminUsersIndexRoute
}

const AppAuthenticatedAdminRouteChildren: AppAuthenticatedAdminRouteChildren = {
  AppAuthenticatedAdminClassesClassIdRoute:
    AppAuthenticatedAdminClassesClassIdRoute,
  AppAuthenticatedAdminBadgesIndexRoute: AppAuthenticatedAdminBadgesIndexRoute,
  AppAuthenticatedAdminClassesIndexRoute:
    AppAuthenticatedAdminClassesIndexRoute,
  AppAuthenticatedAdminImportsIndexRoute:
    AppAuthenticatedAdminImportsIndexRoute,
  AppAuthenticatedAdminMediaAssetsIndexRoute:
    AppAuthenticatedAdminMediaAssetsIndexRoute,
  AppAuthenticatedAdminSettingsIndexRoute:
    AppAuthenticatedAdminSettingsIndexRoute,
  AppAuthenticatedAdminSubjectsIndexRoute:
    AppAuthenticatedAdminSubjectsIndexRoute,
  AppAuthenticatedAdminUsersIndexRoute: AppAuthenticatedAdminUsersIndexRoute,
}

const AppAuthenticatedAdminRouteWithChildren =
  AppAuthenticatedAdminRoute._addFileChildren(
    AppAuthenticatedAdminRouteChildren,
  )

interface AppAuthenticatedTeacherRouteChildren {
  AppAuthenticatedTeacherQuizzesIndexRoute: typeof AppAuthenticatedTeacherQuizzesIndexRoute
  AppAuthenticatedTeacherSubjectsIndexRoute: typeof AppAuthenticatedTeacherSubjectsIndexRoute
  AppAuthenticatedTeacherSubjectsSubjectIdIndexRoute: typeof AppAuthenticatedTeacherSubjectsSubjectIdIndexRoute
  AppAuthenticatedTeacherSubjectsSubjectIdQuizIdIndexRoute: typeof AppAuthenticatedTeacherSubjectsSubjectIdQuizIdIndexRoute
  AppAuthenticatedTeacherSubjectsSubjectIdStudentsIndexRoute: typeof AppAuthenticatedTeacherSubjectsSubjectIdStudentsIndexRoute
}

const AppAuthenticatedTeacherRouteChildren: AppAuthenticatedTeacherRouteChildren =
  {
    AppAuthenticatedTeacherQuizzesIndexRoute:
      AppAuthenticatedTeacherQuizzesIndexRoute,
    AppAuthenticatedTeacherSubjectsIndexRoute:
      AppAuthenticatedTeacherSubjectsIndexRoute,
    AppAuthenticatedTeacherSubjectsSubjectIdIndexRoute:
      AppAuthenticatedTeacherSubjectsSubjectIdIndexRoute,
    AppAuthenticatedTeacherSubjectsSubjectIdQuizIdIndexRoute:
      AppAuthenticatedTeacherSubjectsSubjectIdQuizIdIndexRoute,
    AppAuthenticatedTeacherSubjectsSubjectIdStudentsIndexRoute:
      AppAuthenticatedTeacherSubjectsSubjectIdStudentsIndexRoute,
  }

const AppAuthenticatedTeacherRouteWithChildren =
  AppAuthenticatedTeacherRoute._addFileChildren(
    AppAuthenticatedTeacherRouteChildren,
  )

interface AppAuthenticatedRouteChildren {
  AppAuthenticatedAdminRoute: typeof AppAuthenticatedAdminRouteWithChildren
  AppAuthenticatedTeacherRoute: typeof AppAuthenticatedTeacherRouteWithChildren
  AppAuthenticatedIndexRoute: typeof AppAuthenticatedIndexRoute
  AppAuthenticatedBadgesUserIdRoute: typeof AppAuthenticatedBadgesUserIdRoute
  AppAuthenticatedClassClassIdRoute: typeof AppAuthenticatedClassClassIdRoute
  AppAuthenticatedProfileUserIdRoute: typeof AppAuthenticatedProfileUserIdRoute
  AppAuthenticatedClassIndexRoute: typeof AppAuthenticatedClassIndexRoute
  AppAuthenticatedLeaderboardsIndexRoute: typeof AppAuthenticatedLeaderboardsIndexRoute
  AppAuthenticatedProfileIndexRoute: typeof AppAuthenticatedProfileIndexRoute
  AppAuthenticatedQuizzesIndexRoute: typeof AppAuthenticatedQuizzesIndexRoute
  AppAuthenticatedSubjectsIndexRoute: typeof AppAuthenticatedSubjectsIndexRoute
  AppAuthenticatedQuizzesQuizIdIndexRoute: typeof AppAuthenticatedQuizzesQuizIdIndexRoute
  AppAuthenticatedSubjectsSubjectIdIndexRoute: typeof AppAuthenticatedSubjectsSubjectIdIndexRoute
  AppAuthenticatedQuizzesQuizIdAttemptsAttemptIdRoute: typeof AppAuthenticatedQuizzesQuizIdAttemptsAttemptIdRoute
  AppAuthenticatedQuizzesQuizIdAttemptsIndexRoute: typeof AppAuthenticatedQuizzesQuizIdAttemptsIndexRoute
  AppAuthenticatedQuizzesQuizIdBuilderIndexRoute: typeof AppAuthenticatedQuizzesQuizIdBuilderIndexRoute
  AppAuthenticatedQuizzesQuizIdPlayIndexRoute: typeof AppAuthenticatedQuizzesQuizIdPlayIndexRoute
  AppAuthenticatedQuizzesQuizIdResultsIndexRoute: typeof AppAuthenticatedQuizzesQuizIdResultsIndexRoute
  AppAuthenticatedSubjectsSubjectIdQuizzesIndexRoute: typeof AppAuthenticatedSubjectsSubjectIdQuizzesIndexRoute
  AppAuthenticatedSubjectsSubjectIdStudentsIndexRoute: typeof AppAuthenticatedSubjectsSubjectIdStudentsIndexRoute
}

const AppAuthenticatedRouteChildren: AppAuthenticatedRouteChildren = {
  AppAuthenticatedAdminRoute: AppAuthenticatedAdminRouteWithChildren,
  AppAuthenticatedTeacherRoute: AppAuthenticatedTeacherRouteWithChildren,
  AppAuthenticatedIndexRoute: AppAuthenticatedIndexRoute,
  AppAuthenticatedBadgesUserIdRoute: AppAuthenticatedBadgesUserIdRoute,
  AppAuthenticatedClassClassIdRoute: AppAuthenticatedClassClassIdRoute,
  AppAuthenticatedProfileUserIdRoute: AppAuthenticatedProfileUserIdRoute,
  AppAuthenticatedClassIndexRoute: AppAuthenticatedClassIndexRoute,
  AppAuthenticatedLeaderboardsIndexRoute:
    AppAuthenticatedLeaderboardsIndexRoute,
  AppAuthenticatedProfileIndexRoute: AppAuthenticatedProfileIndexRoute,
  AppAuthenticatedQuizzesIndexRoute: AppAuthenticatedQuizzesIndexRoute,
  AppAuthenticatedSubjectsIndexRoute: AppAuthenticatedSubjectsIndexRoute,
  AppAuthenticatedQuizzesQuizIdIndexRoute:
    AppAuthenticatedQuizzesQuizIdIndexRoute,
  AppAuthenticatedSubjectsSubjectIdIndexRoute:
    AppAuthenticatedSubjectsSubjectIdIndexRoute,
  AppAuthenticatedQuizzesQuizIdAttemptsAttemptIdRoute:
    AppAuthenticatedQuizzesQuizIdAttemptsAttemptIdRoute,
  AppAuthenticatedQuizzesQuizIdAttemptsIndexRoute:
    AppAuthenticatedQuizzesQuizIdAttemptsIndexRoute,
  AppAuthenticatedQuizzesQuizIdBuilderIndexRoute:
    AppAuthenticatedQuizzesQuizIdBuilderIndexRoute,
  AppAuthenticatedQuizzesQuizIdPlayIndexRoute:
    AppAuthenticatedQuizzesQuizIdPlayIndexRoute,
  AppAuthenticatedQuizzesQuizIdResultsIndexRoute:
    AppAuthenticatedQuizzesQuizIdResultsIndexRoute,
  AppAuthenticatedSubjectsSubjectIdQuizzesIndexRoute:
    AppAuthenticatedSubjectsSubjectIdQuizzesIndexRoute,
  AppAuthenticatedSubjectsSubjectIdStudentsIndexRoute:
    AppAuthenticatedSubjectsSubjectIdStudentsIndexRoute,
}

const AppAuthenticatedRouteWithChildren =
  AppAuthenticatedRoute._addFileChildren(AppAuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppAuthenticatedRoute: AppAuthenticatedRouteWithChildren,
  AboutIndexRoute: AboutIndexRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  HelpIndexRoute: HelpIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  LogoutIndexRoute: LogoutIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
  VerifyEmailIndexRoute: VerifyEmailIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
